language: python
python:
  - "3.7"

env:
  global:
    - ANDROID_HOME=/opt/android-sdk-28
    - ANDROID_SDK_ROOT=/opt/android-sdk-28

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - pip install --user ansible
  - touch $HOME/.android/repositories.cfg

install:
  - pip install --user buildozer==1.0.0
  - ansible-galaxy install -r ansible-requirements.yml

before_script:
  - ansible-playbook -c local ansible/bootstrap.yml
  - (while sleep 3; do echo "..."; done) &
  - buildozer init

script:
  - buildozer android debug

after_success:
  - ls -l $HOME/.local/share/python-for-android/dists/

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $HOME/.local/share/python-for-android/dists/*.apk
  skip_cleanup: true
  on:
    tags: true 
